"use client";

import { useState } from "react";
import type { Employee } from "@/data/employees";
import { signOut } from "@/server/auth";

type Section = "Overview" | "Employees" | "Learning & development" | "Interviews & placements" | "Attendance & leave";
type Tab = "Overview" | "Employment" | "Training" | "Skills & evaluation" | "Current work" | "Interviews" | "Attendance";
const tabs: Tab[] = ["Overview", "Employment", "Training", "Skills & evaluation", "Current work", "Interviews", "Attendance"];
const paths: Record<string, string> = {
  Overview: "M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z",
  Employees: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M20 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75",
  "Learning & development": "m2 8 10-5 10 5-10 5z M6 10v7c4 3 8 3 12 0v-7 M22 8v8",
  "Interviews & placements": "M8 6V3h8v3 M3 7h18v14H3z M3 12c6 3 12 3 18 0 M10 12h4v4h-4z",
  "Attendance & leave": "M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 14h2 M14 14h2 M8 18h2",
  search: "m21 21-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0",
};
function Icon({ name }: { name: string }) { return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] || paths.Overview} /></svg>; }
function Avatar({ employee, large = false }: { employee: Employee; large?: boolean }) { return <span className={`avatar ${employee.color} ${large ? "large" : ""}`}>{employee.initials}</span>; }
function Badge({ children }: { children: string }) { return <span className={`badge ${children === "On project" || children.startsWith("Ready") || children === "Recorded" ? "green" : children === "In training" || children === "Scheduled" ? "blue" : children === "Not selected" || children === "Missing record" ? "rose" : "amber"}`}><span className="dot" />{children}</span>; }
function Empty({ message }: { message: string }) { return <div className="empty"><span>○</span><h3>Nothing here yet</h3><p>{message}</p></div>; }
const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));

export default function Portal({ employees }: { employees: Employee[] }) {
  const [section, setSection] = useState<Section>("Overview");
  const [selected, setSelected] = useState<Employee | null>(null);
  const [tab, setTab] = useState<Tab>("Overview");
  const [query, setQuery] = useState("");
  const [team, setTeam] = useState("All teams");
  const [status, setStatus] = useState("All statuses");
  const [notice, setNotice] = useState("");
  const visible = employees.filter(e => `${e.name} ${e.title} ${e.id} ${e.skills.map(s => s.name).join(" ")}`.toLowerCase().includes(query.toLowerCase()) && (team === "All teams" || e.team === team) && (status === "All statuses" || e.status === status));
  const trainings = employees.flatMap(employee => employee.training.map(training => ({ employee, training })));
  const interviews = employees.flatMap(employee => employee.interviews.map(interview => ({ employee, interview })));
  const totals = employees.reduce((a, e) => ({ worked: a.worked + e.attendance.worked, leave: a.leave + e.attendance.leave, missing: a.missing + e.attendance.unrecorded }), { worked: 0, leave: 0, missing: 0 });
  function navigate(value: Section) { setSection(value); setSelected(null); setNotice(""); }
  function open(employee: Employee, nextTab: Tab = "Overview") { setSelected(employee); setTab(nextTab); setNotice(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function exportDirectory() {
    const rows = [["Employee ID", "Name", "Designation", "Team", "Status", "Email"], ...visible.map(e => [e.id, e.name, e.title, e.team, e.status, e.email])];
    const csv = rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\r\n");
    const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" })); link.href = url; link.download = "bs23-demo-employees.csv"; link.click(); URL.revokeObjectURL(url); setNotice(`Exported ${visible.length} demo employee records.`);
  }
  const employeeTable = <div className="table-scroll"><table><thead><tr><th>Employee</th><th>Designation & team</th><th>Core skills</th><th>Current status</th><th><span className="sr-only">Profile</span></th></tr></thead><tbody>{visible.map(e => <tr key={e.id}><td><button className="person-button" onClick={() => open(e)}><Avatar employee={e} /><span><strong>{e.name}</strong><small>{e.id} · {e.type}</small></span></button></td><td><strong className="regular">{e.title}</strong><small>{e.team}</small></td><td><div className="tags">{e.skills.slice(0, 2).map(s => <span key={s.name}>{s.name}</span>)}</div></td><td><Badge>{e.status}</Badge></td><td><button className="arrow-button" onClick={() => open(e)} aria-label={`View ${e.name}'s profile`}>↗</button></td></tr>)}</tbody></table>{visible.length === 0 && <Empty message="No employees match these filters. Try another name, skill or team." />}</div>;
  const filters = <div className="filters"><label className="search-box"><Icon name="search" /><input aria-label="Search employees" placeholder="Search by name, skill or employee ID…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Filter by team" value={team} onChange={e => setTeam(e.target.value)}><option>All teams</option>{[...new Set(employees.map(e => e.team))].map(t => <option key={t}>{t}</option>)}</select><select aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}><option>All statuses</option><option>On project</option><option>In training</option><option>Available</option></select>{(query || team !== "All teams" || status !== "All statuses") && <button className="text-button" onClick={() => { setQuery(""); setTeam("All teams"); setStatus("All statuses"); }}>Reset</button>}</div>;

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">23</span><span>brain station <b>23</b><small>PEOPLE & DEVELOPMENT</small></span></div><div className="workspace"><span className="workspace-icon">L&D</span><div><strong>Learning & Development</strong><small>Manager workspace</small></div></div><p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{(Object.keys(paths).filter(k => k !== "search") as Section[]).map(name => <button key={name} className={section === name ? "nav-item active" : "nav-item"} onClick={() => navigate(name)} aria-current={section === name ? "page" : undefined}><Icon name={name} /><span>{name}</span>{name === "Employees" && <span className="nav-count">{employees.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-card"><span className="dot" /><strong>Demo workspace</strong><p>Explore with fictional employee records.</p></div><div className="admin-identity"><span className="avatar lavender">AK</span><div><strong>Ayesha Karim</strong><small>L&D administrator · demo</small></div></div><form action={signOut}><button className="sign-out">Sign out <span>↗</span></button></form></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{selected ? "Employee profile" : section}</strong></div><div className="topbar-right"><span className="demo-pill">SYNTHETIC DATA</span><form action={signOut} className="mobile-sign-out"><button className="text-button">Sign out</button></form><span className="avatar lavender mini">AK</span></div></header><main className="content">
  {notice && <p className="notice" role="status">{notice}</p>}
  {selected ? <>
    <button className="text-button back" onClick={() => setSelected(null)}>← Back to {section.toLowerCase()}</button>
    <section className="profile-header"><Avatar employee={selected} large /><div className="profile-title"><span className="eyebrow">EMPLOYEE PROFILE · {selected.id}</span><h1>{selected.name}</h1><p>{selected.title} <span>·</span> {selected.team}</p><div className="profile-meta"><span>{selected.location}</span><span>Joined {date(selected.joined)}</span></div></div><Badge>{selected.status}</Badge></section>
    <div className="tabs" role="tablist" aria-label="Employee details">{tabs.map(t => <button key={t} id={`tab-${t.replaceAll(" ", "-")}`} role="tab" aria-selected={tab === t} aria-controls="profile-panel" className={tab === t ? "selected" : ""} onClick={() => setTab(t)}>{t}</button>)}</div>
    <section id="profile-panel" role="tabpanel" aria-labelledby={`tab-${tab.replaceAll(" ", "-")}`}>
    {tab === "Overview" && <div className="detail-grid"><article className="panel"><h2>About {selected.name.split(" ")[0]}</h2><p className="body-copy">{selected.summary}</p><dl className="details"><div><dt>Email address</dt><dd><a href={`mailto:${selected.email}`}>{selected.email}</a></dd></div><div><dt>Employment type</dt><dd>{selected.type}</dd></div><div><dt>Reporting manager</dt><dd>{selected.manager}</dd></div><div><dt>Office</dt><dd>{selected.location}</dd></div></dl></article><article className="panel"><div className="panel-title"><h2>Development snapshot</h2><span className="badge blue">L&D REVIEW</span></div><h3 className="readiness">{selected.review.readiness}</h3><p className="body-copy">{selected.review.next}</p><small>Reviewed {date(selected.review.date)} · {selected.review.reviewer}</small><button className="text-button spaced" onClick={() => setTab("Skills & evaluation")}>View assessment →</button></article><article className="panel"><h2>Current focus</h2><h3>{selected.work.project}</h3><p className="body-copy">{selected.work.update}</p><button className="text-button" onClick={() => setTab("Current work")}>Explore current work →</button></article><article className="panel"><h2>Learning journey</h2>{selected.training.map(t => <div className="learning-mini" key={t.name}><strong>{t.name}</strong><div className="progress-line"><progress value={t.progress} max={100} aria-label={`${t.name} completion`} /><small>{t.progress}%</small></div></div>)}<button className="text-button" onClick={() => setTab("Training")}>View training history →</button></article></div>}
    {tab === "Employment" && <article className="panel"><h2>Employment history</h2><p className="muted">Current role and previous employment.</p><div className="timeline">{selected.history.map(h => <div className="timeline-item" key={h.company}><span className="timeline-dot" /><small>{h.period}</small><h3>{h.role}</h3><strong>{h.company}</strong><p>{h.detail}</p></div>)}</div></article>}
    {tab === "Training" && <article className="panel"><h2>Training & development</h2><p className="muted">Programmes completed and learning currently in progress.</p>{selected.training.map(t => <div className="training-row" key={t.name}><span className="course-icon"><Icon name="Learning & development" /></span><div className="grow"><h3>{t.name}</h3><p>{t.provider}</p><small>{t.progress === 100 ? "Completed" : "Target completion"}: {date(t.date)}</small><div className="progress-line"><progress value={t.progress} max={100} aria-label={`${t.name} completion`} /><small>{t.progress}%</small></div></div><Badge>{t.result}</Badge></div>)}</article>}
    {tab === "Skills & evaluation" && <div className="detail-grid"><article className="panel"><h2>Assessed skills</h2><p className="muted">1 foundational · 2 developing · 3 independent · 4 advanced · 5 expert</p>{selected.skills.map(s => <div className="skill-row" key={s.name}><div><strong>{s.name}</strong><small>{s.evidence}</small></div><span className="skill-rating" aria-label={`${s.level} out of 5`}>{Array.from({ length: 5 }, (_, i) => <i key={i} className={i < s.level ? "filled" : ""} />)}</span></div>)}</article><article className="panel"><h2>Manager evaluation</h2><small>{date(selected.review.date)} · {selected.review.reviewer}</small><h3>Strengths</h3><p className="body-copy">{selected.review.strengths}</p><h3>Development priorities</h3><p className="body-copy">{selected.review.next}</p><div className="callout">{selected.review.readiness}</div><p className="fine-print">A role-specific, human-reviewed assessment. Git activity and attendance are not used to generate an employee score.</p></article></div>}
    {tab === "Current work" && <div className="detail-grid"><article className="panel"><span className="eyebrow">CURRENT ASSIGNMENT</span><h2>{selected.work.project}</h2><dl className="details"><div><dt>Responsibility</dt><dd>{selected.work.role}</dd></div><div><dt>Client allocation</dt><dd>{selected.work.allocation}%</dd></div><div><dt>Latest update</dt><dd>{selected.work.update}</dd></div></dl></article><article className="panel"><h2>Recorded Git activity</h2><div className="big-number">{selected.work.commits}<span>commits</span></div><p className="muted">{selected.work.period}</p><div className="callout">Sample activity · GitHub is not connected</div><p className="body-copy">Commit counts show recorded activity, not work quality or days worked. Design, mentoring and other contributions may not appear in Git.</p></article></div>}
    {tab === "Interviews" && <article className="panel"><h2>External job interviews</h2><p className="muted">Opportunities at other employers, separate from internal assignments.</p>{selected.interviews.length === 0 ? <Empty message="No external job applications or interviews have been recorded for this employee." /> : selected.interviews.map(i => <div className="interview-detail" key={i.company}><div className="panel-title"><h3>{i.company}</h3><Badge>{i.outcome}</Badge></div><p>{i.role}</p><small>{date(i.date)} · {i.stage}</small><div className="callout">{i.feedback}</div><small>Offer / joining date: not recorded</small></div>)}</article>}
    {tab === "Attendance" && <><div className="stat-grid"><Stat label="Scheduled days" value={selected.attendance.scheduled} note="1–20 September 2026" icon="Attendance & leave" /><Stat label="Recorded days worked" value={selected.attendance.worked} note="From demo attendance records" icon="Employees" /><Stat label="Leave days" value={selected.attendance.leave} note="Within the reporting period" icon="Attendance & leave" /><Stat label="Missing records" value={selected.attendance.unrecorded} note="Require review" icon="Overview" /></div><article className="panel"><h2>Leave & attendance exceptions</h2><p className="muted">Schedule: Monday–Friday · demonstration period, not a payroll calculation.</p><div className="table-scroll"><table><thead><tr><th>Date</th><th>Record type</th><th>Days</th><th>Status</th></tr></thead><tbody>{selected.attendance.records.map(r => <tr key={r.date}><td>{date(r.date)}</td><td>{r.type}</td><td>{r.days}</td><td><Badge>{r.status}</Badge></td></tr>)}</tbody></table></div></article></>}
    </section>
  </> : <>
    <div className="page-heading"><div><span className="eyebrow">PEOPLE & DEVELOPMENT</span><h1>{section === "Overview" ? "A clearer view of your people." : section}</h1><p>{section === "Overview" ? "Track progress, support growth and help your people take their next step." : section === "Employees" ? "Every person, their experience and their potential — in one place." : "A shared view of development, opportunities and employee records."}</p></div>{(section === "Overview" || section === "Employees") && <button className="secondary" onClick={exportDirectory}>↓ Export directory</button>}</div>
    {section === "Overview" && <><div className="period-label">WORKSPACE SNAPSHOT <span>Demo period · September 2026</span></div><div className="stat-grid"><Stat label="Total employees" value={employees.length} note="Across 5 specialist teams" icon="Employees" /><Stat label="Learning in progress" value={trainings.filter(t => t.training.progress < 100).length} note="Active training enrolments" icon="Learning & development" /><Stat label="Available for assignment" value={employees.filter(e => e.status === "Available").length} note="Ready for a new opportunity" icon="Overview" /><Stat label="Upcoming interviews" value={interviews.filter(i => i.interview.outcome === "Scheduled").length} note="External employer opportunities" icon="Interviews & placements" /></div><div className="overview-grid"><article className="panel focus-panel"><div className="panel-title"><h2>Growth starts with a next step.</h2><span className="spark">✳</span></div><p>Connect each employee's skills and experience with the right learning opportunity.</p><button className="primary" onClick={() => navigate("Learning & development")}>Explore learning progress <span>→</span></button><div className="focus-foot"><span className="overlap-avatars">{employees.slice(0, 3).map(e => <Avatar key={e.id} employee={e} />)}</span><span>{trainings.filter(t => t.training.progress === 100).length} completed training records</span></div></article><article className="panel attention"><div className="panel-title"><h2>On your radar</h2><span className="badge amber">FOLLOW UP</span></div><button className="radar-row" onClick={() => open(employees[0], "Interviews")}><span className="radar-icon blue"><Icon name="Interviews & placements" /></span><span><strong>Nadia's technical interview</strong><small>23 Sep · Northstar Labs · external employer</small></span><span>↗</span></button><button className="radar-row" onClick={() => open(employees[2], "Training")}><span className="radar-icon lavender"><Icon name="Learning & development" /></span><span><strong>Meera's learning check-in</strong><small>Review communication training progress</small></span><span>↗</span></button><button className="radar-row" onClick={() => navigate("Attendance & leave")}><span className="radar-icon peach"><Icon name="Attendance & leave" /></span><span><strong>{totals.missing} attendance records to review</strong><small>Missing entries in the demo reporting period</small></span><span>↗</span></button></article></div></>}
    {(section === "Employees" || section === "Overview") && <section className="panel directory"><div className="panel-title"><div><h2>Employee directory <span className="count">{employees.length}</span></h2><p className="muted">Get to know the people behind the work.</p></div>{section === "Overview" && <button className="text-button" onClick={() => navigate("Employees")}>View directory →</button>}</div>{filters}{employeeTable}<div className="table-footer">Showing {visible.length} of {employees.length} employees <span>All records are fictional</span></div></section>}
    {section === "Learning & development" && <section className="panel"><div className="panel-title"><h2>Training programmes</h2><span className="badge blue">{`${trainings.length} enrolments`}</span></div><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Programme</th><th>Progress</th><th>Completion / target</th></tr></thead><tbody>{trainings.map(({ employee: e, training: t }) => <tr key={e.id + t.name}><td><button className="person-button" onClick={() => open(e, "Training")}><Avatar employee={e} /><strong>{e.name}</strong></button></td><td><strong className="regular">{t.name}</strong><small>{t.provider}</small></td><td><div className="progress-line"><progress max={100} value={t.progress} aria-label={`${e.name}: ${t.name}`} /><small>{t.progress}%</small></div></td><td>{date(t.date)}</td></tr>)}</tbody></table></div></section>}
    {section === "Interviews & placements" && <section className="panel"><h2>External opportunities</h2><p className="muted">Applications and interview outcomes at other employers. Select an employee to review feedback.</p><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Employer & position</th><th>Interview date</th><th>Outcome</th></tr></thead><tbody>{interviews.map(({ employee: e, interview: i }) => <tr key={e.id + i.company}><td><button className="person-button" onClick={() => open(e, "Interviews")}><Avatar employee={e} /><strong>{e.name}</strong></button></td><td>{i.company}<small>{i.role}</small></td><td>{date(i.date)}</td><td><Badge>{i.outcome}</Badge></td></tr>)}</tbody></table></div></section>}
    {section === "Attendance & leave" && <><div className="stat-grid three"><Stat label="Recorded days worked" value={totals.worked} note="Sum across employees" icon="Employees" /><Stat label="Leave days" value={totals.leave} note="Sum across employees" icon="Attendance & leave" /><Stat label="Missing records" value={totals.missing} note="Require manual review" icon="Overview" /></div><section className="panel"><h2>Attendance summary</h2><p className="muted">1–20 September 2026 · Monday–Friday schedule · synthetic attendance records</p><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Scheduled</th><th>Worked</th><th>Leave</th><th>Missing</th></tr></thead><tbody>{employees.map(e => <tr key={e.id}><td><button className="person-button" onClick={() => open(e, "Attendance")}><Avatar employee={e} /><strong>{e.name}</strong></button></td><td>{e.attendance.scheduled}</td><td>{e.attendance.worked}</td><td>{e.attendance.leave}</td><td><span className="badge amber">{e.attendance.unrecorded}</span></td></tr>)}</tbody></table></div><p className="fine-print">Worked days come from attendance records, not Git commits or scheduled days minus leave.</p></section></>}
  </>}
  <footer className="page-footer"><span>Brain Station 23 · People & Development</span><span>Demo workspace · fictional records · September 2026</span></footer>
  </main></div></div>;
}
function Stat({ label, value, note, icon }: { label: string; value: number; note: string; icon: string }) { return <article className="stat-card"><div><span>{label}</span><Icon name={icon} /></div><strong>{value.toString().padStart(2, "0")}</strong><small>{note}</small></article>; }
